### ISSUE TITLE
Default value for relationship ListOf

### ISSUE THREAD

**Issue by neyasov** [jhthorsen/mandel#18]
Hi!
This is a bug or normal behavior?

Exemple 1:
Person document { _id: '...', name: Alex, cats: [] }
$person->push_cats($cat);
result { _id: '..', name: Alex, cats: [{'$ref': '...', {'$id': '...'} }] }

Exemple 2:
Person document { _id: '..', name: Alex }
$person->push_cats($cat);
result { _id: '...', name: Alex }, { _id: '...', name: Alex }

**Comment by jhthorsen** [comment]
No idea why I reopened this. Closing it again.
