### ISSUE TITLE
Fails with Mojolicious 5.73 and later

### ISSUE THREAD

**Issue by andk** [jhthorsen/mandel#23]
As per subject. Sample fail reports:

5.73: http://www.cpantesters.org/cpan/report/51120188
5.81: http://www.cpantesters.org/cpan/report/51792876

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by jhthorsen** [comment]
Thanks, this should be fixed in 5e0fa0a.
